version: '2'

services:
  pihole:
    image: diginc/pi-hole:debian
    container_name: pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8053:80/tcp
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: 192.168.1.8
      DNS1: 8.26.56.26 
      DNS2: 8.8.4.4
    volumes:
      - ./adlists.list:/etc/pihole/adlists.list
    restart: always
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.1.8:514"