
pihole:
  image: diginc/pi-hole:debian
  container_name: pihole
  ports:
    - 53:53/tcp
    - 53:53/udp
    - 8053:80/tcp
  cap_add:
    - NET_ADMIN
  environment:
    ServerIP: 192.168.1.8
    DNS1: 80.67.169.12 
    DNS2: 80.67.169.40
  volumes:
    - ./adlists.list:/etc/pihole/adlists.list
  restart: always
